package controller;

/**
 * This class allows parts to be specified as inHouse with a corresponding machineID
 */
public class inHouse extends Part{

    private int machineID;

    /**
     * Constructor for the inHouse part
     * @param id id for inhouse part is autogenerated unless being modified
     * @param name defines a name for the inHouse part
     * @param price defines a price for the inHouse part
     * @param stock defines an inventory level for the inHouse part
     * @param min defines a minimum amount for the inHouse part
     * @param max defines a maximum amount for the inHouse part
     * @param machineID defines a machineID for all inHouse parts
     */
    public inHouse(int id, String name, double price, int stock, int min, int max, int machineID) {
        super(id, name, price, stock, min, max);
        this.machineID = machineID;
    }

    /**
     * Returns the Machine ID to make it accessible in other classes
     * @return unique identifier for inHouse parts
     */
    public int getMachineID() {
        return machineID;
    }

    /**
     * sets the machineID
     * @param machineID unique identifier for inHouse parts
     */
    public void setMachineID(int machineID) {
        this.machineID = machineID;
    }
}
